---
name: Tie-FileLRUCache
version: 1.05
author:
  - Benjamin Franz <snowhare@nihongo.org>
abstract: A lightweight but robust filesystem based persistent LRU cache
license: perl
requires:
  Class::ParmList: 1.03
  Digest::SHA1: 0
  File::Temp: 0
  Storable: 0
  Test::More: 0
provides:
  Tie::FileLRUCache:
    file: lib/Tie/FileLRUCache.pm
    version: 1.05
generated_by: Module::Build version 0.261
